{% set version = "3.0.0" %}

package:
  name: sarif-tools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sarif-tools/sarif_tools-{{ version }}.tar.gz
  sha256: 88049665d14afe40e8d455d4bc77c46c0d7b571a0d55db707577b0c1f74e56d7

build:
  number: 0
  entry_points:
    - sarif = sarif.cmdline.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - jinja2 >=3.1.4,<4.0.0
    - jsonpath-ng >=1.6.0,<1.7.0
    - matplotlib-base >=3.7,<4.0.0
    - python >=3.8
    - python-docx >=1.1.2,<2
    - pyyaml >=6.0.1,<7.0.0

test:
  requires:
    - pip
    - m2-grep  # [win]
  imports:
    - sarif
  commands:
    - pip check
    - sarif --version
    - sarif --help
    - sarif --version | grep -iE "^sarif-tools version {{ version.replace(".", "\\.") }}$"

about:
  home: https://github.com/microsoft/sarif-tools
  summary: SARIF tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
