{% set version = "2.0.0" %}

package:
  name: sarif-tools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sarif-tools/sarif_tools-{{ version }}.tar.gz
  sha256: aae95d255b5e5c989a2043d5441f24a727117da0f49f8cad1e7faf7c69eac3a3

build:
  entry_points:
    - sarif = sarif.cmdline.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - jinja2 >=3.1.2,<4.0.0
    - jsonpath-ng >=1.6.0,<1.7.0
    - matplotlib-base >=3.5.1,<4.0.0
    - python >=3.8
    - python-docx >=0.8.11,<0.9.0
    - pyyaml >=6.0.1,<7.0.0


test:
  requires:
    - pip
    - m2-grep  # [win]
  imports:
    - sarif
  commands:
    - pip check
    - sarif --version
    - sarif --help
    - sarif --version | grep -iE "^sarif-tools version {{ version.replace(".", "\\.") }}$"

about:
  home: https://github.com/microsoft/sarif-tools
  summary: SARIF tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
